# Generated by Django 5.2.5 on 2025-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('drink', 'Drink'), ('comida', 'Comida'), ('sobremesa', 'Sobremesa')], default='comida', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/img/', verbose_name='Imagem'),
        ),
    ]
