# Generated by Django 5.2.5 on 2025-09-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_categoria_alter_receita_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('sobremesa', 'Sobremesa'), ('comida', 'Comida'), ('drink', 'Drink')], default='comida', max_length=20, verbose_name='Categoria'),
        ),
    ]
