# Generated by Django 5.2.5 on 2025-09-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_receita_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('drink', 'Drink'), ('sobremesa', 'Sobremesa')], default='comida', max_length=20, verbose_name='Categoria'),
        ),
    ]
